$(document).ready(function(){
      $("#c40").click(function(){
        $(this).popover();
      });
      $("#c38").click(function(){
        $(this).popover();
      });
      $("#c36").click(function(){
        $(this).popover();
      });
      $("#c34").click(function(){
        $(this).popover();
      });
      $("#c32").click(function(){
        $(this).popover();
      });
      $("#c30").click(function(){
        $(this).popover();
      });
      $("#c28").click(function(){
        $(this).popover();
      });
      $("#c26").click(function(){
        $(this).popover();
      });
      $("#c24").click(function(){
        $(this).popover();
      });
      $("#c22").click(function(){
        $(this).popover();
      });
      $("#c20").click(function(){
        $(this).popover();
      });
      $("#c18").click(function(){
        $(this).popover();
      });
      $("#c16").click(function(){
        $(this).popover();
      });
      $("#c14").click(function(){
        $(this).popover();
      });
      $("#c12").click(function(){
        $(this).popover();
      });
      $("#c10").click(function(){
        $(this).popover();
      });
      $("#c8").click(function(){
        $(this).popover();
      });
      $("#c6").click(function(){
        $(this).popover();
      });
      $("#c4").click(function(){
        $(this).popover();
      });
      $("#c2").click(function(){
        $(this).popover();
      });

  });
